mysite/lists/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views

app_name = 'lists'
urlpatterns = [
    url(r'^$',views.IndexView.as_view(), name='index'),
    url(r'^register/$',views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^search/$', views.search,name='search'),
    url(r'^newlist/(?P<item_id>[0-9]+)$', views.create_and_add, name='newlist'),
    url(r'^newlist/$', views.create_list, name='newlist'),
    url(r'^add/(?P<list_id>[0-9]+)/(?P<item_id>[0-9]+)$', views.add_item, name='add'),
    url(r'^remove_item/(?P<list_id>[0-9]+)/(?P<item_id>[0-9]+)$', views.remove_item, name='remove_item'),
    url(r'^details/(?P<type>[A-Z]{1}[a-z]+)/(?P<ran1>[0-9]+)/(?P<ran2>[0-9]+)$',views.item_view,name='details'),
    url(r'^detail/(?P<list_id>[0-9]+)$', views.list_view, name='detail'),
    url(r'^visibility/(?P<list_id>[0-9]+)$', views.visibility, name='visibility'),
    url(r'^delete/(?P<list_id>[0-9]+)$', views.delete, name='delete'),
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^lists/',include('lists.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite/lists/models.py
from __future__ import unicode_literals
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from lists.choices import *
import json

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User)

    list_count = models.IntegerField(default=0)
    server = models.IntegerField(choices=SERVER_CHOICES, default=0)
    mp = models.CharField(max_length=100,blank=True,null=True)
        
    def __unicode__(self):
        return self.user.username

class List(models.Model):
    list_name = models.CharField(max_length=100)
    user = models.ForeignKey(User)
    server = models.IntegerField(choices=SERVER_CHOICES, default=0)
    pub_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    public = models.BooleanField(default=True)
    list_display = ('list_name', 'user')
    def __unicode__(self):
        return self.list_name
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Objet(models.Model):
    ID = models.PositiveIntegerField(primary_key=True)
    name = models.CharField(max_length=100,db_index=True)
    level = models.PositiveSmallIntegerField(default=0)
    type = models.CharField(max_length=50)
    effects = models.TextField()
    caracs = models.TextField()
    conds = models.TextField()
    recipe = models.TextField()
    list_display = ('ID')
    def __unicode__(self):
        return str(self.ID)

class ListItem(models.Model):
    ID = models.ForeignKey(List)
    itemID = models.ForeignKey(Objet)
    count = models.PositiveSmallIntegerField(default = 0)
    priority = models.PositiveSmallIntegerField(default = 0)
    value = models.PositiveIntegerField(default = 0)
    list_display = ('ID')
    def __unicode__(self):
            return str(self.ID)

class Recette(models.Model):
    item_ID =  models.ForeignKey('Objet',related_name="item_ID")
    ing_ID =  models.ForeignKey('Objet',related_name="ing_ID")
    count = models.PositiveSmallIntegerField(default=0)
    list_display = ('item_ID')
    def __unicode__(self):
        return str(self.item_ID)

mysite/lists/forms.py
from lists.models import UserProfile, List
from django.contrib.auth.models import User
from django import forms
from lists.choices import *


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')
        labels = {
            'username': 'Nom d\'utilisateur',
            'email' : 'Adresse email',
            'password': 'Mot de passe',
        }

class UserProfileForm(forms.ModelForm):
    server = forms.ChoiceField(choices = SERVER_CHOICES, initial='0', widget=forms.Select())
    class Meta:
        model = UserProfile
        fields = ('server', 'mp')
        labels = {
            'server': 'Serveur',
            'mp': 'Pseudo in-game',
        }
class NewListForm(forms.ModelForm):
    class Meta:
        model = List
        fields = ('list_name','public')
        labels = {
            'list_name': 'Nom',
            'public' : 'Liste publique'
        }
        help_texts = {
            'public': 'Une liste publique permet aux autres utilisateurs de voir votre liste.<br> Ils pourront aussi voir votre serveur et nom in-game si ceux-ci figurent sur votre profil.',
        }

class EditListForm(forms.ModelForm):
    class Meta:
        model = List
        fields = ('list_name','server')
        labels = {
            'list_name': 'Nom',
            'server' : 'Serveur'
        }

class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email',)
        labels = {
            'email': 'Adresse email'
        }

mysite/lists/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import get_object_or_404,render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone
from .models import User,List,UserProfile, ListItem, Objet
from .forms import *
from django.template import RequestContext

# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     context = {'latest_question_list': latest_question_list}
#     return render(request,'lists/index.html',context)
#
# def detail(request,question_id):
#     question = get_object_or_404(Question,pk=question_id)
#     return render(request,'lists/detail.html',{'question':question})
# def results(request,question_id):
#     question = get_object_or_404(Question,pk=question_id)
#     return render(request,'lists/results.html',{'question':question})

class IndexView(generic.ListView):
    template_name = 'lists/index.html'
    context_object_name = 'lists'

    def get_queryset(self):
        return List.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')

class DetailView(generic.DetailView):
    model = List
    template_name = 'lists/detail.html'

def register(request):

    context = RequestContext(request)

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            profile.save()
            registered = True
        else:
            print user_form.errors, profile_form.errors

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request,
            'lists/register.html',
            {'user_form': user_form, 'profile_form': profile_form, 'registered': registered}, context)


def user_login(request):
    context = RequestContext(request)
    error = False
    active = True
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/lists/')
            else:
                active = False
        else:
            print "Mauvais nom d'utilisateur ou mot de passe: {0}, {1}".format(username, password)
            error = True

    return render(request,'lists/login.html', {'error': error, 'active':active}, context)

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/lists/')

@login_required
def create_list(request):
    context = RequestContext(request)
    completed=False
    if request.method == 'POST':
        list_form = NewListForm(data=request.POST)
        if list_form.is_valid():
            newlist = list_form.save(commit=False)
            newlist.user = request.user
            serv = UserProfile.objects.filter(user__exact=request.user)
            if serv:
                newlist.server = serv[0].server
            newlist.save()
            completed=True

        else:
            print list_form.errors
    else:
        list_form = NewListForm()
    dict_ret = {'newlist': True, 'list_form': list_form,'completed':completed}
    url =  request.META['HTTP_REFERER']
    dict_ret.update({'url' : url})
    if 'next' in request.GET:
        return redirect(request.GET['next'],dict_ret,context)
    return render(request,'lists/index.html',dict_ret,context)

@login_required
def create_and_add(request,item_id):
    context = RequestContext(request)

    completed=False
    added = False
    if request.method == 'POST':
        list_form = NewListForm(data=request.POST)
        if list_form.is_valid():
            newlist = list_form.save(commit=False)
            newlist.user = request.user
            serv = UserProfile.objects.filter(user__exact=request.user)
            if serv:
                newlist.server = serv[0].server

            newl = newlist.save()
            item_list = ListItem()
            item_list.itemID_id = item_id
            item_list.ID_id = newlist.id
            item_list.save()
            completed=True
            added = True
        else:
            print list_form.errors
    else:
        list_form = NewListForm()

    dict_ret = {'newlist': True, 'list_form': list_form,'completed':completed,'added':added,'item_id' : item_id}

    url =  request.META['HTTP_REFERER']
    dict_ret.update({'url' : url})
    if 'next' in request.GET:
        return redirect(request.GET['next'],dict_ret,context)
    return render(request,'lists/index.html',dict_ret,context)


def item_view(request,type,ran1,ran2):
    context = RequestContext(request)
    if type == "Epee":
        ret = 'Épée'
    elif type == "Sac":
        ret = 'Sac à dos'
    elif type == "Baton":
        ret = "Bâton"
    elif type == "Trophee":
        ret = "Trophée"
    else:
        ret = type
    ran = [ran1,ran2]
    return render(request,'lists/index.html',{'type': ret, 'ran': ran},context)

@login_required
def add_item(request,list_id,item_id):
    context = RequestContext(request)
    item = ListItem()
    listObj = List.objects.get(pk=list_id)
    itemObj = Objet.objects.get(ID=item_id)
    item.ID = listObj
    item.itemID = itemObj
    item.save()
    dict_ret = {'added': True}
    url =  request.META['HTTP_REFERER']
    p = url.split("lists")
    if "details" in p[1]:
        p = p[1].split("/")
        if "page" in p[4]:
            n = p[4].split('=')[1]
        else:
            n = 1
        add_dict = {'type': p[2], 'ran': [p[3],p[4].split("?")[0]],'page': n}
        dict_ret.update(add_dict)
    return render(request,'lists/index.html',dict_ret,context)

def list_view(request,list_id):
    context = RequestContext(request)
    edited = False
    liste = List.objects.get(pk=list_id)
    if request.method == 'POST':
        edit_form = EditListForm(data=request.POST)
        if edit_form.is_valid():
            edit = edit_form.save(commit=False)
            liste.server = edit.server
            liste.list_name = edit.list_name
            liste.save()
            edited = True
        else:
            print edit_form.errors
    else:
        edit_form = EditListForm(initial={'list_name': liste.list_name, 'server': liste.server})
    return render(request,'lists/index.html',{'list_id': list_id,'edit_form': edit_form, 'edited': edited},context)

@login_required
def remove_item(request,list_id,item_id):
    context = RequestContext(request)
    listObj = ListItem.objects.filter(ID_id=list_id).filter(itemID_id = item_id)
    if listObj is not None:
        listObj[0].delete()
    url =  request.META['HTTP_REFERER']

    return redirect(url,{"itemRemoved": True})

@login_required
def visibility(request,list_id):
    context = RequestContext(request)
    liste = List.objects.get(pk=list_id)
    url =  request.META['HTTP_REFERER']
    print url

    if liste.user == request.user:
        if liste.public:
            liste.public = False
        else:
            liste.public = True
        liste.save()
        return redirect(url,{'changed':True})
    else:
        return redirect(url,{'changed':False})

@login_required
def delete(request,list_id):
    context = RequestContext(request)
    liste = List.objects.get(pk=list_id)
    if liste.user == request.user:
        liste.delete()
        return render(request,'lists/index.html',{'listRemoved':True},context)
    else:
        url =  request.META['HTTP_REFERER']
        return redirect(url,{'listError': True})

@login_required
def profile(request):

    context = RequestContext(request)
    user = request.user
    profile = UserProfile.objects.get(user=user)
    modified = False

    if request.method == 'POST':
        edit_user_form = EditUserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)
        if edit_user_form.is_valid() and profile_form.is_valid():
            edit_user = edit_user_form.save(commit=False)
            edit_profile = profile_form.save(commit=False)
            profile.server = edit_profile.server

            profile.mp = edit_profile.mp
            profile.save()
            user.set_password(edit_user.password)
            user.email = edit_user.email
            edited = True
        else:
            print profile_form.errors, edit_user_form.errors
    else:
        profile_form = UserProfileForm(initial={'mp': profile.mp, 'server': profile.server})
        edit_user_form = EditUserForm(initial={'email': user.email})
    return render(request,
            'lists/profile.html',
            {'profile_form': profile_form,'edit_user_form': edit_user_form, 'modified': modified}, context)


def search(request):
    query = request.GET.get('search')

    return render(request, 'lists/index.html', {'query': query})

mysite/lists/templates/includes/add_button.html
{% load lists_extra %}

{% if user.is_authenticated %}
<div class="dropdown">
  <div class="btn dropdown-toggle form-control top" type="button" data-toggle="dropdown">
    <span class="glyphicon glyphicon-plus-sign" style="color:#00ff00"></span></div>
    <ul class="dropdown-menu scrollable-menu">
      <li class="dropdown-header">Ajouter à</li>
      <li class="list-group-item"><a data-toggle="myModal" href="{% url 'lists:newlist' item.ID %}">Nouvelle liste</a></li>

        {% if myLists %}
            {% for list in myLists %}
              <li class="list-group-item"><a href="{% url 'lists:add' list.id item.ID %}">{{ list.list_name }}</a></li>
            {% endfor %}
            {% endif %}
  </div>
  {% endif %}

mysite/lists/templates/includes/edit_list.html
{% load staticfiles %}
{% load bootstrap %}
<form role="form" class="form-horizontal" id="edit_list_form" method="post" action="/lists/edit_list/" enctype="multipart/form-data">

  {% csrf_token %}
  {{ edit_list_form|bootstrap_horizontal }}
  <div class="form-group">
    <div class="col-sm-10 col-sm-offset-2">
      <input type="submit" class="btn btn-primary" name="submit" value="Sauvegarder" />
    </div>
  </div>
</form>

mysite/lists/templates/includes/footer.html
<footer class="footer" id="foot">
     <div class="container">
       <p class="text-muted">Images © Ankama Games</p>
       <p class="text-muted">Tous les éléments, fonctionnalités, outils, documents qui font partie de l'univers de DOFUS sont la propriété exclusive d'Ankama Game.</p>

     </div>
   </footer>

mysite/lists/templates/includes/list_view.html
{% load lists_extra %}
{% load bootstrap %}

<div class="row">
  <div class="col-md-12">
    <h2>Liste "{{myList.list_name}}"</h2><p style="color:gray">
      Créée par {{myList.user}} {% if myList.user|get_mp %} /w {{myList.user|get_mp}} {% endif %}
    </p>
  </div>
</div>
<br>
<div class="row">
  <div class="col-md-12">

    <div class="btn-group btn-group-justified">

      {% if user|verified:myList %}

      <a type="button" class="btn btn-primary" data-toggle="collapse" data-target="#total_auth">Total des ingrédients</a>
      <a type="button" class="btn btn-primary" data-toggle="collapse" data-target="#import">Importer</a>
      <a type="button" class="btn btn-primary" data-toggle="collapse" data-target="#edit">Éditer</a>
      <a type="button" class="btn btn-success" data-toggle="collapse" data-target="#share">Partager</a>

      {% if myList.public %}
      <a href="{% url 'lists:visibility' myList.id %}" type="button" class="btn btn-warning">Rendre privée</a>
      {% else %}
      <a href="{% url 'lists:visibility' myList.id %}" type="button" class="btn btn-success">Publier</a>
      {% endif %}

      <a href="{% url 'lists:delete' myList.id %}" type="button" class="btn btn-danger">Supprimer</a>
      {% else %}
      <a type="button" class="btn btn-primary" data-toggle="collapse" data-target="#total_pub">Total des ingrédients</a>
      <a type="button" class="btn btn-success" data-toggle="collapse" data-target="#share">Partager</a>

      {% endif %}
    </div>
  </div>
</div>

<br>

<div id="total_pub" class="collapse row">
  <div class="col-sm-1"></div>
  <div class="col-sm-10">

  <ul class="list-group">
    <li class="list-group-item col-md-12" style="text-align:center;font-weight:bold">Liste des ingrédients</li>

  {% for r in items|get_total %}
    <li class="list-group-item col-md-6">
  {{r.count}} {{r.item.name}}</li>
  {% endfor %}
  </ul>
  </div>
  <div class="col-sm-1"></div>
</div>

<div id="total_auth" class="collapse row">
  <div class="col-sm-1"></div>
  <div class="col-sm-10">

  <ul class="list-group">
    <li class="list-group-item col-md-12" style="text-align:center;font-weight:bold">Liste des ingrédients</li>
  {% for r in items|get_total %}
    <li class="list-group-item col-md-6">

  <form role = "form" class="form-recipe">
    <input type = "number" class = "input-mini" min="0" max ={{r.count}}>
  </form>/
  {{r.count}} {{r.item.name}}</li>
  {% endfor %}
  </ul>
  </div>
<div class="col-sm-1"></div>
</div>

<div id="import" class="collapse">
  <form role = "form" class="form-inline">
    <label for="imp">URL à importer:</label><br>
    <input type="text" class="form-control" id="imp">
    <button type="submit" class="btn btn-default">Importer</button>
  </form>

</div>

<div id="edit" class="collapse">
  <form role="form" class="form-horizontal" id="user_list" method="post" action="{{path}}" enctype="multipart/form-data">

    {% csrf_token %}
    {% if edit_form %}
    {{ edit_form|bootstrap_horizontal }}
      {% endif %}
    <div class="form-group">
      <div class="col-sm-10 col-sm-offset-2">
        <input type="submit" class="btn btn-primary" name="submit" value="Sauvegarder" />
      </div>
    </div>
  </form>

</div>

<div id="share" class="collapse">

  <input type="text" class="form-control" value="{{ path }}">

</div>

<br>
{% for l in items|get_item %}

<ul class="list-group">
  <li class="list-group-item top">
    <div class="row">

      <div class="col-md-7 vertical">{{l.name}}</div>
      <div class="col-md-2 vertical">Niveau: {{l.level}}</div>

      <div class="col-md-3" align="right">
        {% if user|verified:myList %}
        Priorité:  <form role = "form" class="form-priority">
          <input type = "number" class = "input-mini" min="0" max =100 style="color:#000">
        </form>
        <a href="{% url 'lists:remove_item' myList.id l.ID %}" title="Supprimer cet objet">
          <span class="glyphicon glyphicon-minus-sign" style="color:#969696"></span></a>
          {% endif %}
        </div>
      </div>
    </li>
    <li class="list-group-item main">
      <div class="row">
        <div class="col-md-4">
          <div class="row">
            <div class="col-md-12">
              <br> IMAGE<br>IMG<br>
              {{l.type}}
            </div>
          </div>
        </div>

        <div class="col-md-5 mid">
          {% if l|get_recipe %}
            {% if user|verified:myList %}
          {% for r in l|get_recipe %}

          <form role = "form" class="form-recipe">
            <input type = "number" class = "input-mini" min="0" max ={{r.count}}>
          </form>/ {{r.count}} {{r.ing_ID.name}}</br>
          {% endfor %}
          {% else%}
          {% for r in l|get_recipe %}
            {{r.count}} {{r.ing_ID.name}}</br>
          {% endfor %}
          {% endif %}
          {% else%}
          <p>Recette indisponible</p>
          {% endif %}

        </div>
        <div class="col-md-3">
          {% if l.effects|parse:"" %}
          <i>Effets:</i> <br>
          {% for s in l.effects|parse:"" %}
          {{s}}<br>
          {% endfor %}
          {% endif %}
        </div>
      </li>

    </ul>
    {% endfor %}

mysite/lists/templates/includes/navbar.html
<nav class="navbar navbar-inverse" data-spy="affix">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'lists:index' %}">To-Dofus</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a data-toggle="myModal" href="{% url 'lists:newlist' %}"><span class="glyphicon glyphicon-plus" title="Nouvelle liste"></span></a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">

      {% if user.is_authenticated %}
        <li><a href="{% url 'lists:profile' %}"><span class="glyphicon glyphicon-user"></span>  {{ user.username }} </a></li>
        <li><a href="{% url 'lists:logout' %}"><span class="glyphicon glyphicon-log-out"></span>&nbsp;&nbsp;Logout</a></li>
      {% else %}
        <li><a href="{% url 'lists:login' %}"><span class="glyphicon glyphicon-log-in"></span>&nbsp;&nbsp;Login</a></li>
      {% endif %}
      <li><a href="{% url 'lists:register' %}"><span class="glyphicon glyphicon-edit"></span>&nbsp;&nbsp;Inscription&nbsp;&nbsp;&nbsp;&nbsp;</a></li>
    </ul>
</nav>

mysite/lists/templates/includes/search.html
{% load staticfiles %}
<br></br>


<h4>Equipements</h4>
<form class="navbar-form navbar-left" role="search" method="GET" action="{% url 'lists:search' %}">
    <div class="form-group" >
        <input type="text" class="form-control" placeholder="Recherche" name ="search">
    </div>
</form>
<ul class="list-group row">
  <li class="list-group-item col-xs-5"><a href="{% url 'lists:details' 'Chapeau' '1' '200' %}"><img src="{% static "lists/images/coiffe.png" %}" width="100%" alt="" /></a></li>
  <li class="list-group-item col-xs-5"><a href="{% url 'lists:details' 'Cape' '1' '200' %}"><img src="{% static "lists/images/cape.png" %}" width="100%" alt="" /></a></li>
  <li class="list-group-item col-xs-5"><a href="{% url 'lists:details' 'Amulette' '1' '200' %}"><img src="{% static "lists/images/amulette.png" %}" width="100%" alt="" /></a></li>
  <li class="list-group-item col-xs-5"><a href="{% url 'lists:details' 'Anneau' '1' '200' %}"><img src="{% static "lists/images/anneau.png" %}" width="100%" alt="" /></a></li>
  <li class="list-group-item col-xs-5"><a href="{% url 'lists:details' 'Ceinture' '1' '200' %}"><img src="{% static "lists/images/ceinture.png" %}" width="100%" alt="" /></a></li>
  <li class="list-group-item col-xs-5"><a href="{% url 'lists:details' 'Bottes' '1' '200' %}"><img src="{% static "lists/images/bottes.png" %}" width="100%" alt="" /></a></li>
  <li class="list-group-item col-xs-5"><a href="{% url 'lists:details' 'Idole' '1' '200' %}"><img src="{% static "lists/images/idole.png" %}" width="100%" alt="" /></a></li>
  <li class="list-group-item col-xs-5"><a href="{% url 'lists:details' 'Trophee' '1' '200' %}"><img src="{% static "lists/images/trophee.png" %}" width="100%" alt="" /></a></li>
  <li class="list-group-item col-xs-5"><a href="{% url 'lists:details' 'Dague' '1' '200' %}"><img src="{% static "lists/images/dague.png" %}" width="100%" alt="" /></a></li>
  <li class="list-group-item col-xs-5"><a href="{% url 'lists:details' 'Epee' '1' '200' %}"><img src="{% static "lists/images/epee.png" %}" width="100%" alt="" /></a></li>
  <li class="list-group-item col-xs-5"><a href="{% url 'lists:details' 'Marteau' '1' '200' %}"><img src="{% static "lists/images/marteau.png" %}" width="100%" alt="" /></a></li>
  <li class="list-group-item col-xs-5"><a href="{% url 'lists:details' 'Pelle' '1' '200' %}"><img src="{% static "lists/images/pelle.png" %}" width="100%" alt="" /></a></li>
  <li class="list-group-item col-xs-5"><a href="{% url 'lists:details' 'Hache' '1' '200' %}"><img src="{% static "lists/images/hache.png" %}" width="100%" alt="" /></a></li>
  <li class="list-group-item col-xs-5"><a href="{% url 'lists:details' 'Bouclier' '1' '200' %}"><img src="{% static "lists/images/bouclier.png" %}" width="100%" alt="" /></a></li>
  <li class="list-group-item col-xs-5"><a href="{% url 'lists:details' 'Baguette' '1' '200' %}"><img src="{% static "lists/images/baguette.png" %}" width="100%" alt="" /></a></li>
  <li class="list-group-item col-xs-5"><a href="{% url 'lists:details' 'Baton' '1' '200' %}"><img src="{% static "lists/images/baton.png" %}" width="100%" alt="" /></a></li>
  <li class="list-group-item col-xs-5"><a href="{% url 'lists:details' 'Arc' '1' '200' %}"><img src="{% static "lists/images/arc.png" %}" width="100%" alt="" /></a></li>
  <li class="list-group-item col-xs-5"><a href="{% url 'lists:details' 'Autres' '1' '200' %}"><img src="{% static "lists/images/autres.png" %}" width="100%" alt="" /></a></li>
  <li class="list-group-item col-xs-5"><a href="{% url 'lists:details' 'Sac' '1' '200' %}"><img src="{% static "lists/images/sac.png" %}" width="100%" alt="" /></a></li>
  <li class="list-group-item col-xs-5"><a href="{% url 'lists:details' 'Consommable' '1' '200' %}"><img src="{% static "lists/images/conso.png" %}" width="100%" alt="" /></a></li>
</ul>

mysite/lists/templates/includes/side_menu.html
{% load lists_extra %}
<h3>Mes listes</h3>
{% if user.is_authenticated %}
  {% if myLists %}
    <ul>

      {% for list in myLists %}
        <li><a href="{% url 'lists:detail' list.id %}">{{ list.list_name }}</a></li>
      {% endfor %}
    </ul>
    {% else %}
      <p>Aucune liste disponible.</p>
  {% endif %}
{% else %}
  <p><a href="{% url 'lists:login'%}">Inscription requise</a></p>
{% endif %}
<h3>Sur mon serveur</h3>
{% if user.is_authenticated %}

{% if serverList %}
<ul>
  {% for l in serverList %}
  {% if l.public %}
  {% if l.user|get_mp %}
    <li><a href="{% url 'lists:detail' l.id %}">{{ l.list_name }},  /w {{l.user|get_mp}}</a></li>
  {% else %}
    <li><a href="{% url 'lists:detail' l.id %}">{{ l.list_name }}</a></li>
  {% endif %}

  {% endif %}
  {% endfor %}
</ul>
{% else %}
<p>Aucun serveur spécifié / Aucune liste pour ce serveur</p>
{% endif %}
{% else %}
  <p><a href="{% url 'lists:login'%}">Inscription requise</a></p>
{% endif %}